$(function(){
	//--
	$('.sNavA').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNavA').eq(i).addClass('aNow');
			   $('.anowyes').removeClass('current');
			   $('.sNav').eq(i).css('left',$(this).offset().left-0);
			   $('.sNav').eq(i).show().stop().animate({top: 112}, 150);
			   },
		   function(){
			   $('.sNavA').removeClass('aNow');
			   $('.anowyes').addClass('current');
			   $('.sNav').hide().stop().animate({top: 60}, 150);
			   }
		)
		})	
	$('.sNav').each(function(i){
		$(this).hover(
		   function(){
			   $('.anowyes').removeClass('current');
			   $('.sNavA').eq(i).addClass('aNow');
			   $(this).show().stop().animate({top: 112}, 150);
			   },
		   function(){
			   $('.sNavA').removeClass('aNow');
			   $('.anowyes').addClass('current');
			   $('.sNav').hide();
			   }
		)
		})
	//--
	var fadeFlashTime=new Array();
	$('.fadeFlash').find('li:first').fadeIn(500);
	$('.fadeFlash').each(function(i){
		fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
		$(this).find('.btnDiv').find('span').each(function(ii){
			$(this).hover(
			function(){
				clearInterval(fadeFlashTime[i]);
				$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
				$(this).addClass('spanNow');
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
				fadeFlashNow[i]=ii;
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
				fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
				},
			function(){}	
				)
			})
		$(this).find('.rightBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]<$('.fadeFlash').eq(i).find('li').length-1){
				fadeFlashNow[i]++;
				}else{
					fadeFlashNow[i]=0;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		$(this).find('.leftBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]>0){
				fadeFlashNow[i]--;
				}else{
					fadeFlashNow[i]=$('.fadeFlash').eq(i).find('li').length-1;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		})
	//--
	$('.contactBox').find('.Close').click(function(){
		$('.mapDiv').find('.tab2').find('li').removeClass('liNow');
		$('.contactBox').hide();
	})

    //--
	$('.mapDiv').find('li').each(function (i) {
	    $(this).hover(
		  function () {
		      $('.mapDiv').find('li').eq(i).addClass('on');
		  },
		  function () {
		      $('.mapDiv').find('li').eq(i).removeClass('on');
		  }
		)
	})
    //--

	//--
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}	
				)
			})
		})
	//--
	$('.tab2').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).click(
			function(){
				$('.tab2').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv2').eq(i).find('.tabContent2').hide();
				$('.tabContentDiv2').eq(i).find('.tabContent2').eq(ii).show();
				}
				)
			})
		})
	//--
	$('.tabContentDiv3').find('.tabContent3:first').show();
	$('.tab3').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).click(
			function(){
				$('.tab3').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv3').eq(i).find('.tabContent3').hide();
				$('.tabContentDiv3').eq(i).find('.tabContent3').eq(ii).show();
				}
				)
			})
		})
	//--
	$(".indexAbout").hover(
	   function(){
		   $(this).find('.box').height($(this).height());
		   $(this).find('.box').fadeIn(200);
		   $(this).find('.title3').fadeOut(200);
		   },
	   function(){
		   $(this).find('.box').fadeOut(200);
		   $(this).find('.title3').fadeIn(200);
		   }
	)
	//--
	$(".indexVideo").hover(
	   function(){
		   $(this).find('.box').height($(this).height());
		   $(this).find('.box').fadeIn(200);
		   $(this).find('.ico').fadeOut(200);
		   },
	   function(){
		   $(this).find('.box').fadeOut(200);
		   $(this).find('.ico').fadeIn(200);
		   }
	)
	//--
	$(".indexCommunity").hover(
	   function(){
		   $(this).find('.box').height($(this).height());
		   $(this).find('.box').fadeIn(200);
		   $(this).find('.name').fadeOut(200);
		   },
	   function(){
		   $(this).find('.box').fadeOut(200);
		   $(this).find('.name').fadeIn(200);
		   }
	)
	$(".indexHonor").hover(
	   function(){
		   $(this).find('.box').height($(this).height());
		   $(this).find('.box').fadeIn(200);
		   $(this).find('.name').fadeOut(200);
		   },
	   function(){
		   $(this).find('.box').fadeOut(200);
		   $(this).find('.name').fadeIn(200);
		   }
	)
	//--
/*	$(".indexResource").hover(
	   function () {
		   $(this).find('.before').fadeOut(200);
	       $(this).find('.later').fadeIn(200);
	   },
	   function () {
		   $(this).find('.before').fadeIn(200);
	       $(this).find('.later').fadeOut(200);
	   }
	)*/
	//--
	$('.indexBrand').hover(
	   function(){
		   $(this).fadeTo(200,0.8);
		   },
	   function(){
		   $(this).fadeTo(200,1);
		   }
	)
	//--
	$('.indexWuye').hover(
	   function(){
		   $(this).fadeTo(200,0.8);
		   },
	   function(){
		   $(this).fadeTo(200,1);
		   }
	)
	//--
	$('.indexResource').find('.later').each(function(i){
	$(this).find('li').hover(
	   function(){
		   $('.indexResource').eq(i).find('li').removeClass('liNow');
		   $(this).addClass('liNow');
		   },
	   function(){}
	)	
	})	
	//--
	$('.projectNav').find('li:last-child').css('border-right','none');
	//--
	$(window).scroll(function(){
		if($(window).scrollTop()>10){
			$('.indexBtn').fadeOut(200);
			}else{
				$('.indexBtn').fadeIn(200);
				}
		})	
	//--
	$('.indexNav').find('a').each(function(i){
		$(this).click(function(){
			$('.indexNav').find('a').removeClass('aNow');
			$('.indexNav').find('a').eq(i).addClass('aNow');
			$('body,html').animate({scrollTop: $('.indexDiv').eq(i).offset().top}, 500);
			})
		})
	$(window).scroll(function(){
	$('.indexDiv').each(function(i){
		if($(window).scrollTop()>=$(this).offset().top-$(window).height()/2){
			$('.indexNav').find('a').removeClass('aNow');
			$('.indexNav').find('a').eq(i).addClass('aNow');
			}
		})		
	})
	//--
	$('.sideBarTelA').hover(
	   function(){
		   $('.sideBarTel').show();
		   },
	   function(){
		   $('.sideBarTel').hide();
		   }
	)
	$('.sideBarTel').hover(
	   function(){
		   $(this).show();
		   },
	   function(){
		   $(this).hide();
		   }
	)
	//--
	$('.pageNav').find('a:last').css('border','0px');	
	//--
	if($('.golfNav').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>440){
				$('.golfNav').addClass('golfNavNow');
				}else{
					$('.golfNav').removeClass('golfNavNow');
					}
			})
		}
	//--
	if($('.sideForm').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>440){
				$('.sideForm').addClass('sideFormNow');
				}else{
					$('.sideForm').removeClass('sideFormNow');
					}
			})
		}
	//--
	if($('.projectSide').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>600){
				$('.projectSide').addClass('projectSideNow');
				}else{
					$('.projectSide').removeClass('projectSideNow');
					}
			})
		}
	//--
	$('.projectSide').find('.list').find('a').each(function(i){
		$(this).click(function(){
			$('.projectSide').find('.list').find('a').removeClass('aNow');
			$('.projectSide').find('.list').find('a').eq(i).addClass('aNow');
			$('body,html').animate({scrollTop: $('.projectPart').eq(i).offset().top-88}, 500);
			})
		})
	$(window).scroll(function(){
	$('.projectPart').each(function(i){
		if($(window).scrollTop()>=$(this).offset().top-$(window).height()/2){
			$('.projectSide').find('.list').find('a').removeClass('aNow');
			$('.projectSide').find('.list').find('a').eq(i).addClass('aNow');
			}
		})		
	})				
	//--
	$('.golfClubList').find('.rightBtn').click(function(){
		imgScrollRight2($('.golfClubList').find('.list'),$('.golfClubList').find('li').length-6,125,0);
		})
	$('.golfClubList').find('.leftBtn').click(function(){
		imgScrollLeft2($('.golfClubList').find('.list'),$('.golfClubList').find('li').length-6,125,0);
		})	
	//--
	$('.projects').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)	
	//--
	$('.projectPart4').find('.btnDiv').each(function(i){
		$(this).find('.rightBtn').click(function(){
			imgScrollRight2($('.projectPart4').find('.list').eq(i),$('.projectPart4').find('.list').eq(i).find('li').length-3,358,i);
			})
		$(this).find('.leftBtn').click(function(){
			imgScrollLeft2($('.projectPart4').find('.list').eq(i),$('.projectPart4').find('.list').eq(i).find('li').length-3,358,i);
			})	
		})	
	//--
	$('.job').find('tr:odd').find('td').css('background','#f7f9fa');			
    //

    //--
	$('.projectChoose').find('a').each(function (i) {
	    $(this).click(function () {
	        $('.projectChoose').find('a').removeClass('aNow');
	        $(this).addClass('aNow');
	        $('body,html').stop().animate({ scrollTop: $('.projectDiv').eq(i).offset().top }, 500, 'easeOutQuart');
	    })
	})

	if ($('.projectChoose').length > 0) {
	    $(window).scroll(function () {
	        if ($(window).scrollTop() > 550) {
	            $('.projectChoose').addClass('projectChooseNow');
	        } else {
	            $('.projectChoose').removeClass('projectChooseNow');
	          
	        }
	        $('.projectDiv').each(function (i) {
	            if ($(window).scrollTop() >= $(this).offset().top) {
	                $('.projectChoose').find('a').removeClass('aNow');
	                $('.projectChoose').find('a').eq(i).addClass('aNow');
	            }
	        })
	    })
	}
    //

	})